version: '3.7'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  server: &server
    build:
      context: ./server
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /server.sh

  client:
    build:
      context: ./client
    depends_on:
      - server
    env_file:
      - .env
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celeryworker:
    <<: *server
    depends_on:
      - redis
      - postgres
    ports: []
    command: /worker.sh

  celerybeat:
    <<: *server
    depends_on:
      - redis
      - postgres
    ports: []
    command: /beat.sh

