# Generated by Django 3.2.6 on 2021-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ebay_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
